# Copyright (C) 2018-2021 Intel Corporation
#
# SPDX-License-Identifier: MIT

version: '3.3'

services:
  cvat_db:
    container_name: cvat_db
    image: postgres:10-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: cvat
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - cvat_db:/var/lib/postgresql/data
    networks:
      - cvat
  cvat_redis:
    container_name: cvat_redis
    image: redis:4.0-alpine
    restart: always
    networks:
      - cvat

  cvat:
    container_name: cvat
    image: cvat_dev:2.0 
    restart: always
    command: sleep 3600
    depends_on:
      - cvat_redis
      - cvat_db
      - cvat_opa
    volumes:
      - .:/code/cvat
    networks:
      - cvat
    ports:
      - 8080:8080
      - 8090:8090

  cvat_opa:
    container_name: cvat_opa
    image: openpolicyagent/opa:0.34.2-rootless
    restart: always
    networks:
      cvat:
        aliases:
          - opa
    volumes:
      - ./cvat/apps/iam/rules:/rules
    ports:
      - '8181:8181'
    command: run --server --addr :8181 --set=decision_logs.console=true /rules


networks:
  cvat:
volumes:
  cvat_db:
